/*                                                                                                                                                                                                                                    
     * Project: Sistem Absensi RFID Sosialisasi SMK                                                                                                                                                                                       
     * Developer: Aditya Febrian                                                                                                                                                                                                          
     * NIM: 240104040129                                                                                                                                                                                                                  
     * Institution: UIN Antasari Banjarmasin                                                                                                                                                                                              
     */                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                             
    #include <WiFi.h>                                                                                                                                                                                                                     
    #include <SPI.h>                                                                                                                                                                                                                      
    #include <MFRC522.h>                                                                                                                                                                                                                  
    #include <WiFiClientSecure.h>                                                                                                                                                                                                         
                                                                                                                                                                                                                                          
    #define RST_PIN 22                                                                                                                                                                                                                    
    #define SS_PIN 5                                                                                                                                                                                                                      
                                                                                                                                                                                                                                          
    #define LED_HIJAU 21                                                                                                                                                                                                                  
    #define LED_MERAH 4                                                                                                                                                                                                                   
                                                                                                                                                                                                                                          
    MFRC522 mfrc522(SS_PIN, RST_PIN);                                                                                                                                                                                                     
                                                                                                                                                                                                                                          
                                                                                                                                                                                                
    const char* ssid = "Wokwi-GUEST";                                                                                                                                                                                                     
    const char* password = "";                                                                                                                                                                                                            
                                                                                                                                                                                                                                          
    const String apiUrl = "https://rfid.ordinaryfeb.xyz/api/rfid/scan";                                                                                                                                                                   
                                                                                                                                                                                                                                          
    void setup() {                                                                                                                                                                                                                        
      Serial.begin(115200);                                                                                                                                                                                                               
                                                                                                                                                                                                                                          
      pinMode(LED_HIJAU, OUTPUT);                                                                                                                                                                                                         
      pinMode(LED_MERAH, OUTPUT);                                                                                                                                                                                                         
      digitalWrite(LED_HIJAU, LOW);                                                                                                                                                                                                       
      digitalWrite(LED_MERAH, LOW);                                                                                                                                                                                                       
                                                                                                                                                                                                                                          
      delay(1000);                                                                                                                                                                                                                        
                                                                                                                                                                                                                                          
      Serial.println("\n==================================");                                                                                                                                                                             
      Serial.println("  Diagnostik HW");                                                                                                                                                                                                  
      Serial.println("==================================");                                                                                                                                                                               
                                                                                                                                                                                                                                          
      SPI.begin();                                                                                                                                                                                                                        
      mfrc522.PCD_Init();                                                                                                                                                                                                                 
                                                                                                                                                                                                                                          
      byte v = mfrc522.PCD_ReadRegister(mfrc522.VersionReg);                                                                                                                                                                              
      if (v == 0x00 || v == 0xFF) {                                                                                                                                                                                                       
        Serial.println("\n[ERR] Komunikasi RFID Gagal. Cek Kabel!");                                                                                                                                                                      
      } else {                                                                                                                                                                                                                            
        Serial.println("[Berhasil] Modul RFID Connected.");                                                                                                                                                                               
      }                                                                                                                                                                                                                                   
      Serial.println("==================================\n");                                                                                                                                                                             
                                                                                                                                                                                                                                          
      WiFi.begin(ssid, password);                                                                                                                                                                                                         
      Serial.print("Menghubungkan ke WiFi");                                                                                                                                                                                              
      while (WiFi.status() != WL_CONNECTED) {                                                                                                                                                                                             
        delay(500);                                                                                                                                                                                                                       
        Serial.print(".");                                                                                                                                                                                                                
      }                                                                                                                                                                                                                                   
      Serial.println("\n WiFi Terhubung!");                                                                                                                                                                                               
      Serial.println("Silahkan Tap Kartu Anda");                                                                                                                                                                                          
    }                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                          
    void loop() {                                                                                                                                                                                                                         
                                                                                                                                                                                                                                          
      byte rfidVersion = mfrc522.PCD_ReadRegister(mfrc522.VersionReg);                                                                                                                                                                    
      if (rfidVersion == 0x00 || rfidVersion == 0xFF) {                                                                                                                                                                                   
                                                                                                                                                                                                                                          
        digitalWrite(LED_MERAH, HIGH);                                                                                                                                                                                                    
        delay(100);                                                                                                                                                                                                                       
        digitalWrite(LED_MERAH, LOW);                                                                                                                                                                                                     
        delay(100);                                                                                                                                                                                                                       
                                                                                                                                                                                                                                          
        mfrc522.PCD_Init();                                                                                                                                                                                                               
        delay(500);                                                                                                                                                                                                                       
        return;                                                                                                                                                                                                                           
      }                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
      if (!mfrc522.PICC_IsNewCardPresent()) return;                                                                                                                                                                                       
      if (!mfrc522.PICC_ReadCardSerial()) return;                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                             
      String uidString = "";                                                                                                                                                                                                              
      for (byte i = 0; i < mfrc522.uid.size; i++) {                                                                                                                                                                                       
        uidString += String(mfrc522.uid.uidByte[i] < 0x10 ? "0" : "");                                                                                                                                                                    
        uidString += String(mfrc522.uid.uidByte[i], HEX);                                                                                                                                                                                 
      }                                                                                                                                                                                                                                   
      uidString.toUpperCase();                                                                                                                                                                                                            
                                                                                                                                                                                                                                          
      Serial.println("\n-------------------------");                                                                                                                                                                                      
      Serial.println("UID Kartu: " + uidString);                                                                                                                                                                                          
                                                                                                                                                                                                                                          
      digitalWrite(LED_HIJAU, HIGH);                                                                                                                                                                                                      
      delay(100);                                                                                                                                                                                                                         
      digitalWrite(LED_HIJAU, LOW);                                                                                                                                                                                                       
                                                                                                                                                                                                                                          
      kirimDataKeServer(uidString);                                                                                                                                                                                                       
                                                                                                                                                                                                                                          
      mfrc522.PICC_HaltA();                                                                                                                                                                                                               
      mfrc522.PCD_StopCrypto1();                                                                                                                                                                                                          
      delay(2000);                                                                                                                                                                                                                        
    }                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                          
    void kirimDataKeServer(String uid) {                                                                                                                                                                                                  
      if (WiFi.status() != WL_CONNECTED) {                                                                                                                                                                                                
        Serial.println("[ERR] WiFi Terputus!");                                                                                                                                                                                           
        return;                                                                                                                                                                                                                           
      }                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                          
      WiFiClientSecure client;                                                                                                                                                                                                            
      client.setInsecure();                                                                                                                                                                                                               
      client.setTimeout(15000);                                                                                                                                                                                                           
                                                                                                                                                                                                                                          
      Serial.print("Menghubungkan ke Hostinger...");                                                                                                                                                                                      
                                                                                                                                                                                                                                          
      if (!client.connect("rfid.ordinaryfeb.xyz", 443)) {                                                                                                                                                                                 
        Serial.println(" GAGAL!");                                                                                                                                                                                                        
        digitalWrite(LED_MERAH, HIGH); delay(1500); digitalWrite(LED_MERAH, LOW);                                                                                                                                                         
        return;                                                                                                                                                                                                                           
      }                                                                                                                                                                                                                                   
      Serial.println(" BERHASIL!");                                                                                                                                                                                                       
                                                                                                                                                                                                                                          
      String payload = "{\"uid\":\"" + uid + "\"}";                                                                                                                                                                                       
                                                                                                                                                                                                                                          
      client.println("POST /api/rfid/scan HTTP/1.1");                                                                                                                                                                                     
      client.println("Host: rfid.ordinaryfeb.xyz");                                                                                                                                                                                       
      client.println("Content-Type: application/json");                                                                                                                                                                                   
      client.println("Accept: application/json");                                                                                                                                                                                         
      client.println("User-Agent: ESP32-HMTI");                                                                                                                                                                                           
      client.print("Content-Length: ");                                                                                                                                                                                                   
      client.println(payload.length());                                                                                                                                                                                                   
      client.println("Connection: close");                                                                                                                                                                                                
      client.println();                                                                                                                                                                                                                   
      client.println(payload);                                                                                                                                                                                                            
                                                                                                                                                                                                                                          
      Serial.print("Menunggu balasan server... ");                                                                                                                                                                                        
                                                                                                                                                                                                                                          
      while (client.connected()) {                                                                                                                                                                                                        
        String line = client.readStringUntil('\n');                                                                                                                                                                                       
        if (line == "\r") {                                                                                                                                                                                                               
          break;                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                 
      }                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                          
      String response = "";                                                                                                                                                                                                               
      unsigned long startMilis = millis();                                                                                                                                                                                                
                                                                                                                                                                                                                                          
      while (millis() - startMilis < 3000) {                                                                                                                                                                                              
        while (client.available()) {                                                                                                                                                                                                      
          response += (char)client.read();                                                                                                                                                                                                
          startMilis = millis();                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                          
        if (response.length() > 0) {                                                                                                                                                                                                      
          break;                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                 
      }                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                          
      Serial.println("\nBalasan Web: " + response);                                                                                                                                                                                       
                                                                                                                                                                                                                                          
      if (response.indexOf("\"success\":true") > 0) {
        digitalWrite(LED_HIJAU, HIGH); delay(1500); digitalWrite(LED_HIJAU, LOW);
      } else {
        digitalWrite(LED_MERAH, HIGH); delay(1500); digitalWrite(LED_MERAH, LOW);
      }
      
      client.stop();
    }
